### ISSUE TITLE
dependency analysis

### ISSUE THREAD

**Issue by pawamoy** [vintasoftware/python-linters-and-code-analysis#12]
Hi! Shameless plug here!

I wrote a tool called [dependenpy](https://github.com/Genida/dependenpy). It's a library and also a CLI tool. It parses the source code (with `ast` module) of given installed packages to build a listing of all the imports, and therefore inter-dependencies between modules or packages.

Would you be interested in listing it here? It never got quite the attention, but I think it's a nice piece of code :slightly_smiling_face: 

The purpose of it was to analyze the inter-dependencies of a Python package to check if it complies with various criteria listed in [The Protection of Information in Computer Systems](https://www.cs.virginia.edu/~evans/cs551/saltzer/). `dependenpy` is only responsible for listing dependencies, and [archan](https://github.com/Genida/archan) is checking the criteria, but I'm only proposing to add `dependenpy` here (`archan` needs reworking).

I'm not sure in which section it would fit though!

That's it!

**Comment by pawamoy** [comment]
I give up, you win :grimacing:

**Comment by fjsj** [comment]
hi @pawamoy , sorry, never received this notification. Please feel free to make a PR including `dependenpy`! I guess it fits better into `Other tools`, right?

**Comment by pawamoy** [comment]
Oh, okay :sweat_smile: Then I'll open a PR, thanks!
